# Generated by Django 6.0.1 on 2026-02-20 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_estudiante_estudiantecarrera_horario_inscripcion_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_estudiante', to='academics.carrera'),
        ),
    ]
