# Generated by Django 5.2 on 2026-01-28 06:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuatrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50)),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(db_index=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuatrimestre',
                'verbose_name_plural': 'Cuatrimestres',
                'ordering': ['-año', '-fecha_inicio'],
                'indexes': [models.Index(fields=['año', 'activo'], name='academics_c_año_fa588b_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='academics_c_fecha_i_738a71_idx')],
                'unique_together': {('nombre', 'año')},
            },
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instituto',
                'verbose_name_plural': 'Institutos',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo', 'activo'], name='academics_i_codigo_0887cb_idx'), models.Index(fields=['nombre'], name='academics_i_nombre_61a648_idx')],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_anios', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('MIXTA', 'Mixta')], default='PRESENCIAL', max_length=20)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('instituto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='academics.instituto')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creditos', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)])),
                ('horas_catedra', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo', 'activa'], name='academics_m_codigo_6d9e25_idx'), models.Index(fields=['nombre'], name='academics_m_nombre_b9ceaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarreraMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cuatrimestre', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('es_obligatoria', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera_materias', to='academics.carrera')),
                ('correlativas', models.ManyToManyField(blank=True, help_text='Materias de la misma carrera que deben aprobarse antes', related_name='es_correlativa_de', to='academics.carreramateria')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrera_materias', to='academics.materia')),
            ],
            options={
                'verbose_name': 'Materia de Carrera',
                'verbose_name_plural': 'Materias de Carreras',
                'ordering': ['carrera', 'año', 'cuatrimestre'],
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='materias',
            field=models.ManyToManyField(related_name='carreras', through='academics.CarreraMateria', to='academics.materia'),
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50)),
                ('capacidad_maxima', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capacidad_actual', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('carrera_materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='academics.carreramateria')),
                ('cuatrimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='academics.cuatrimestre')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['cuatrimestre', 'carrera_materia', 'nombre'],
                'indexes': [models.Index(fields=['carrera_materia', 'cuatrimestre', 'activa'], name='academics_c_carrera_389f40_idx'), models.Index(fields=['capacidad_actual'], name='academics_c_capacid_59cf41_idx')],
                'unique_together': {('carrera_materia', 'cuatrimestre', 'nombre')},
            },
        ),
        migrations.AddIndex(
            model_name='carreramateria',
            index=models.Index(fields=['carrera', 'año', 'es_obligatoria'], name='academics_c_carrera_f8a1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='carreramateria',
            index=models.Index(fields=['materia'], name='academics_c_materia_123c01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carreramateria',
            unique_together={('carrera', 'materia')},
        ),
        migrations.AddIndex(
            model_name='carrera',
            index=models.Index(fields=['codigo', 'activo'], name='academics_c_codigo_d90eef_idx'),
        ),
        migrations.AddIndex(
            model_name='carrera',
            index=models.Index(fields=['instituto', 'activo'], name='academics_c_institu_52da27_idx'),
        ),
        migrations.AddIndex(
            model_name='carrera',
            index=models.Index(fields=['nombre'], name='academics_c_nombre_acf558_idx'),
        ),
    ]
