# Generated by Django 5.2 on 2026-02-03 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='carrera_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='academics.carreramateria'),
        ),
    ]
