# Generated by Django 6.0.1 on 2026-02-20 17:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_comision_carrera_materia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Estado académico del estudiante')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['legajo'],
            },
        ),
        migrations.CreateModel(
            name='EstudianteCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(db_index=True, default=True, help_text='Indica si es la carrera activa del estudiante')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='academics.carrera')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='academics.estudiante')),
            ],
            options={
                'verbose_name': 'Carrera del Estudiante',
                'verbose_name_plural': 'Carreras de Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], db_index=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.CharField(blank=True, help_text='Aula o espacio de cursada', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academics.comision')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['comision', 'dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='academics.comision')),
                ('estudiante_carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='academics.estudiantecarrera')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PARCIAL_1', 'Parcial 1'), ('PARCIAL_2', 'Parcial 2'), ('RECUPERATORIO', 'Recuperatorio'), ('FINAL', 'Examen Final'), ('TP', 'Trabajo Práctico'), ('OTRO', 'Otro')], db_index=True, max_length=20)),
                ('nota', models.DecimalField(decimal_places=2, help_text='Nota (escala 0-10)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('fecha', models.DateField(db_index=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academics.inscripcion')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['inscripcion', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='MateriaAprobada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aprobacion', models.DateField()),
                ('nota', models.PositiveSmallIntegerField(help_text='Nota final (escala 1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('condicion', models.CharField(choices=[('REGULAR', 'Regular'), ('PROMOCIONADO', 'Promocionado'), ('EQUIVALENCIA', 'Equivalencia')], db_index=True, default='REGULAR', max_length=20)),
                ('acta_numero', models.CharField(blank=True, help_text='Número de acta de examen', max_length=50)),
                ('estudiante_carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias_aprobadas', to='academics.estudiantecarrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprobaciones', to='academics.materia')),
            ],
            options={
                'verbose_name': 'Materia aprobada',
                'verbose_name_plural': 'Materias aprobadas',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('titulo_profesional', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Estado del profesor')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AddField(
            model_name='comision',
            name='profesor',
            field=models.ForeignKey(blank=True, help_text='Profesor a cargo de la comisión', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='academics.profesor'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['legajo', 'activo'], name='academics_e_legajo_9859c9_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiantecarrera',
            index=models.Index(fields=['estudiante', 'activa'], name='academics_e_estudia_c05d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiantecarrera',
            index=models.Index(fields=['carrera', 'activa'], name='academics_e_carrera_c8b79a_idx'),
        ),
        migrations.AddConstraint(
            model_name='estudiantecarrera',
            constraint=models.UniqueConstraint(fields=('estudiante', 'carrera'), name='unique_estudiante_carrera'),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['comision', 'dia_semana'], name='academics_h_comisio_90a460_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['estudiante_carrera', 'activa'], name='academics_i_estudia_b3c170_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['comision', 'activa'], name='academics_i_comisio_4647d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('estudiante_carrera', 'comision'), name='unique_inscripcion_estudiante_comision'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['inscripcion', 'tipo'], name='academics_c_inscrip_d3a394_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['fecha'], name='academics_c_fecha_ebe107_idx'),
        ),
        migrations.AddIndex(
            model_name='materiaaprobada',
            index=models.Index(fields=['estudiante_carrera', 'materia'], name='academics_m_estudia_d60dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='materiaaprobada',
            index=models.Index(fields=['fecha_aprobacion'], name='academics_m_fecha_a_3a24c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='materiaaprobada',
            constraint=models.UniqueConstraint(fields=('estudiante_carrera', 'materia'), name='unique_materia_aprobada_por_estudiante'),
        ),
        migrations.AddIndex(
            model_name='profesor',
            index=models.Index(fields=['legajo', 'activo'], name='academics_p_legajo_8c3f6f_idx'),
        ),
    ]
