# Generated by Django 5.2 on 2026-02-20 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_estudiante_estudiantecarrera_horario_inscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='cuatrimestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='academics.cuatrimestre'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='academics.materia'),
        ),
        migrations.AlterField(
            model_name='carreramateria',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrera_materias', to='academics.carrera'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['materia', 'cuatrimestre', 'activa'], name='academics_i_materia_68b5a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('estudiante_carrera', 'materia', 'cuatrimestre'), name='unique_inscripcion_activa_por_materia_cuatrimestre'),
        ),
    ]
